#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

#update the nginx configuration file to add the redirect rule
sudo bash -c "cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.hackertyper.com;
    }
}
EOF"

# Restart Nginx to apply the changes
sudo service nginx restart

