#!/usr/bin/env bash
#a script that prints out a loop using else and elif
i=0
while [ $i -lt 10 ]
do
i=$((i+1))
if [ $i -eq 4 ]; then
 echo "bad luck"
 elif [ $i -eq 8 ]; then
 echo "good luck"
 else
 echo "Best School"
 fi
done
