#!/usr/bin/env bash

# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080.

# Change the user directive in the Nginx configuration file
sed -i 's/user  nginx;/user nginx;/' /etc/nginx/nginx.conf

# Change the listen directive in the Nginx default server block configuration file
sed -i 's/listen       80;/listen 8080 default_server;/' /etc/nginx/conf.d/default.conf

# Restart the Nginx service
service nginx restart

