#!/usr/bin/env bash

# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080.

sed -i 's/user  nginx;/user  nginx;\n/g' /etc/nginx/nginx.conf

# Change ownership of the Nginx directories to the nginx user
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx

# Update the Nginx service to use the new configuration
systemctl restart nginx.service

